### ISSUE TITLE
Expliziter Default-Konstruktor unnötig.

### ISSUE THREAD

**Issue by wi7e** [tpe-lecture/group-25#3]
ein expliziter Default Konstruktor ohne zusätzliche Funktion bringt auch keinen Nutzen da er so auch implizit aufgerufen wird.

**Comment by theSimit66** [comment]
Der Konstruktor ohne Parameter füllt die Werte des Vectors mit null , da der Nullvector durch dies referenziert wird . 
Issue3 completed!
