### ISSUE TITLE
Nicht abgefangener Fehler in Methode Einheitsvektor

### ISSUE THREAD

**Issue by wi7e** [tpe-lecture/group-25#4]
public Vector einheitsvektor() {
double ein = 1 / this.betrag();

-> falls "this.betrag()" 0 ist, kommt es an dieser Stelle zu einem mathematischen Fehler. Sollte durch eine Exception abgefangen werden.

**Comment by theSimit66** [comment]
Im Einheitsvektor wurde der fehler durch try and catch abgefangen.
Issue3 completed!
