### ISSUE TITLE
Objekte der Klasse Vektor sollten vor Veränderungen geschützt werden

### ISSUE THREAD

**Issue by wi7e** [tpe-lecture/group-25#6]
Laut JavaDoc: "Objekte dieser Klasse sind immutable. Die Methoden verändern den Zustand des Objektes nicht sondern geben ein neues Objekt zurück."

in eurer aktuellen Implementierung lassen sich Objektattribute jedoch von aussen zugreifen (manipulieren)

**Comment by theSimit66** [comment]
Wir wissen nicht welches Objekt wir verändern  oder ob wir ein objekt verändern sollen.
